site:
  name: Pere Villega
  site: 'https://perevillega.com'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Pere Villega
    template: '%s â€” Pere Villega'
  description: "Principal Engineer & Technical Consultant. Software Engineering, Architecture, and Freelance Services."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Pere Villega
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@paborji'
    site: '@paborji'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 10

    post:
      isEnabled: true
      permalink: '/blog/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: true

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null
    umami:
      id: '7bdfa858-bebc-479d-9a1f-bea833a709a8'
      src: 'https://umami.villegawilcz.com/script.js'

ui:
  theme: 'system'
